### ISSUE TITLE
User can send notice to restaurant

### ISSUE THREAD

**Issue by Janae2020** [We-cool/what-s-open#1]
When the user finds a restaurant that they would either like to either sit down and eat at, they have the  option to alert the restaurant and let them know that they are on their way and how far out they are (by minutes) for the location.

**Comment by BulldogBiggs** [comment]
Using the map, a user can select a restaurant and view its details

**Comment by codepathreview** [comment]
Looks like you are missing the following deliverables:

- Schema: Data Models
- Schema: Networking
- Sprint Plan: GitHub Issues created from user stories
- Sprint Plan: Issues added to project and assigned to specific team members

Your group milestone is incomplete until all the [required deliverables](https://courses.codepath.org/snippets/android_university/readme_templates/project_1_readme.md) are complete. Once completed, please push your updates, update your README, your project board, and [submit your group milestone](https://courses.codepath.org/courses/android_university/pages/submitting_assignments) again using the submit button on the appropriate assignment page so we can regrade it.

Whenever you make updates to your project that require re-grading, you need to **re-submit** your project using the submit button on the associated assignment page in the course portal. This will flag your project as “updated” on our end and we know to re-grade.

You should re-submit your assignment anytime you:
- Update a previously incomplete assignment
- Add optional and additional features to an already completed assignment 
/cc @codepathreview

**Comment by codepathreview** [comment]
Looks like you are missing the following deliverables:

- Sprint planned for next week -- Issues created, assigned & added to project board
- Completed user stories checked-off in README
- Gifs created to show build progress and added to README

Your group milestone is incomplete until all the [required deliverables](https://courses.codepath.org/snippets/android_university/readme_templates/project_1_readme.md) are complete. Once completed, please push your updates, update your README, your project board, and [submit your group milestone](https://courses.codepath.org/courses/android_university/pages/submitting_assignments) again using the submit button on the appropriate assignment page so we can regrade it.

Whenever you make updates to your project that require re-grading, you need to **re-submit** your project using the submit button on the associated assignment page in the course portal. This will flag your project as “updated” on our end and we know to re-grade.

You should re-submit your assignment anytime you:
- Update a previously incomplete assignment
- Add optional and additional features to an already completed assignment 
/cc @codepathreview

**Comment by Janae2020** [comment]
﻿Thank you for the feedback. However I seem to be doing this group assignment alone because I’m getting no help from my group. So I’m lost on how to do things such as “how to make a correct schema” and the power-points are not helping at all. I’m just a senior trying to pass this class and graduate

**Comment by codepathreview** [comment]
Looks like you are missing the following deliverables:

- Completed user stories checked-off in README
- Gifs created to show build progress and added to README

Your assignment is incomplete until all the [deliverables](https://courses.codepath.org/snippets/android_university/readme_templates/project_1_readme.md) are complete. Once completed, please push your updates, update your README, update your project board, and [submit your group milestone](https://courses.codepath.org/courses/android_university/pages/submitting_assignments) again using the submit button on the appropriate assignment page so we can regrade it.

We have also read your feedback and have already forwarded it to your TF so he can look into the issue and fix it asap.
 
/cc @codepathreview

**Comment by Janae2020** [comment]
How do I update that I completed at task on my github

**Comment by codepathreview** [comment]
Looks like you are missing the following deliverables:

- Sprint planned for next week -- Issues created, assigned & added to project board
- Completed user stories checked-off in README
- Gifs created to show build progress and added to README

Your assignment is incomplete until all the [deliverables](https://courses.codepath.org/snippets/android_university/readme_templates/project_1_readme.md) are complete. Once completed, please push your updates, update your README, update your project board, and [submit your group milestone](https://courses.codepath.org/courses/android_university/pages/submitting_assignments) again using the submit button on the appropriate assignment page so we can regrade it.

Whenever you make updates to your project that require re-grading, you need to **re-submit** your project using the submit button on the associated assignment page in the course portal. This will flag your project as “updated” on our end and we know to re-grade.

You should re-submit your assignment anytime you:
- Update a previously incomplete assignment
- Add optional and additional features to an already completed assignment 
/cc @codepathreview
